_wandb:
    value:
        cli_version: 0.23.0
        e:
            khwt0p6ufqtxkenyz22b6eir0ea7zbs7:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: train2.py
                codePathLocal: train2.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "135326932992"
                email: 20075186@tafe.wa.edu.au
                executable: /Users/shannonrobinson/miniforge3/envs/pytorch_env_at2/bin/python
                host: Shannons-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/shannonrobinson/Library/CloudStorage/OneDrive-TAFE/Sem2/managing-data/mac_pytorch_at2/train2.py
                python: CPython 3.10.19
                root: /Users/shannonrobinson/Library/CloudStorage/OneDrive-TAFE/Sem2/managing-data/mac_pytorch_at2
                startedAt: "2025-11-30T10:00:32.723854Z"
                writerId: khwt0p6ufqtxkenyz22b6eir0ea7zbs7
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.19
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
batch_size:
    value: 128
data_dir:
    value: data
epochs:
    value: 20
lr:
    value: 0.01
momentum:
    value: 0.9
num_workers:
    value: 4
output_dir:
    value: outputs
seed:
    value: 42
val_split:
    value: 0.1
wandb_name:
    value: run
wandb_project:
    value: pytorch_cifar10_workflow
weight_decay:
    value: 0.0005
